### ISSUE TITLE
Crash when try enable Thea Render Plugin

### ISSUE THREAD

**Issue by Akiyamka** [schroef/Thea4Blender#3]
OS: Windows 10 (x64)
Blender: v.2.78
TheaForBlender: v1.5.07.755.1447 (Downloaded from official site)
Traceback:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\Akiya\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\TheaForBlender\__init__.py", line 55, in <module>
    from . import thea_properties
  File "C:\Users\Akiya\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\TheaForBlender\thea_properties.py", line 1115, in <module>
    items=getTheaCRFMenuItems(),
  File "C:\Users\Akiya\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\TheaForBlender\thea_render_main.py", line 3215, in getTheaCRFMenuItems
    if len(dataPath ) > 5:
TypeError: object of type 'NoneType' has no len()
```

**Comment by schroef** [comment]
Hi Akiyamka, sorry i should take this code down. Header over to [this one](https://github.com/grakoczy/TheaForBlender) PS you do need to get plugin through that link, you need darkroom. It wont work without.

But some items needs studio, like the CRF error. Thats Camera Repsonse Filter, those are film effects. They come with thea studio.

But you can use it without. Also edit material externally wont work cause you need the material editor which also comes with thea studio. You can how ever make materials inside blender, you will be limited as a couple items cant be ported at the moment. But thats just a few items.

**Comment by schroef** [comment]
This was a earlier version, we are now using the other. BUt you need to get the version through the link.

**Comment by schroef** [comment]
PS you also need to follow the link at the bottom of the page, to get the darkroom. Without it, nothing will happen.
